services:
  - type: web
    name: project-management-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: project-db
          property: connectionString
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: project-db
    databaseName: projectdb
    user: project_user
    plan: free