# Generated by Django 5.2.4 on 2025-08-04 14:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('timelogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelog',
            options={'verbose_name': 'Time Log', 'verbose_name_plural': 'Time Logs'},
        ),
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together={('task', 'user')},
        ),
    ]
