# Generated by Django 5.2.4 on 2025-08-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_repr',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
